---
version: '3'
services:
  minecraft:
    image: eendroroy/minecraft-server:latest
    volumes:
      - './worlds:/worlos:rw'
    ports:
      - "25565:25565"
    expose:
      - "25565"
    environment:
      - SERVER_PORT=25565
